### ISSUE TITLE
Add support for configuring kubernetes startup probe

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-charts#32]
**Is your feature request related to a problem? Please describe.**

Kubernetes define a specific startup probe for applications that are slow to start:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes

We should provide a way to define such a probe from the Helm Chart.

This would add a `deploy.startupProbe` whose content will be a YAML configuration of the startup probe as defined in https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes

**Comment by jmesnil** [comment]
This feature would follow up what we did for readiness and liveness probes:

* Add templating code to include a startupProbe if `deploy.startupProbe` is defined (similar to https://github.com/wildfly/wildfly-charts/blob/98e86bb0dd24d7c75131df6d764b9644eeb1a4b5/charts/wildfly-common/templates/_deployment.yaml#L61-L64)
* Provide a default value in https://github.com/wildfly/wildfly-charts/blob/98e86bb0dd24d7c75131df6d764b9644eeb1a4b5/charts/wildfly/values.yaml#L27 (similar to `readinessProbe`) with maybe a higher `failureThreshold: 18` so that the app has 3 minutes (18 * 10 = 180s) to startup.
* Add doc in https://github.com/wildfly/wildfly-charts/blob/main/charts/wildfly/README.md (similar to `deploy.readinessProbe`)
* Add schema validation in https://github.com/wildfly/wildfly-charts/blob/98e86bb0dd24d7c75131df6d764b9644eeb1a4b5/charts/wildfly/values.schema.json#L509 (but we don't provide the full validation schema for k8s probes)

**Comment by yersan** [comment]
This is superseded by https://github.com/wildfly/wildfly-charts/issues/37
