### ISSUE TITLE
GALLEON_PROVISION_DEFAULT_FAT_SERVER is useless

### ISSUE THREAD

**Issue by jfdenise** [wildfly/wildfly-charts#94]
Setting this env variable is useless with WildFly s2i V2 and shouldn't be added by Helm Charts.

**Comment by jmesnil** [comment]
@jfdenise  isn't that still useful if the Helm Chart is using S2I environment variables to set up the feature packs and layers?

**Comment by jmesnil** [comment]
should I keep it only if `.build.s2i.galleonLayers` is defined?

**Comment by jfdenise** [comment]
It is no more used. used to be needed when the default server was a "thin" server that we were not able to copy over the runtime image. mainly used with Openshift templates. Yo ucan safely remove it in all cases.
